### ISSUE TITLE
Doesn't work on package build

### ISSUE THREAD

**Issue by zakkar** [RLoris/FileHelperDoc#2]
Hi there,

Actually to save some time  downloaded the plugins, but it seem like the project cannot packaged with this plugin enabled. The main issue is that there's already a FileHelper class created within Unreal which I think, conflict when creating a package version. As a fix I renamed the plugin, if it can help here's the error 

Note also that I used the 4.27 version

s (64-bit)):     [1/3] Module.FileHelper.cpp
UATHelper: Packaging (Windows (64-bit)):     /Plugins/FileHelperPlugin/Source/FileHelper/Private/FileHelper.cpp(9): error C2653: 'FFileHelperModule': is not a class or namespace name
UATHelper: Packaging (Windows (64-bit)):     /Plugins/FileHelperPlugin/Source/FileHelper/Private/FileHelper.cpp(15): error C2653: 'FFileHelperModule': is not a class or namespace name
UATHelper: Packaging (Windows (64-bit)):    /Plugins/FileHelperPlugin/Source/FileHelper/Private/FileHelper.cpp(24): error C2065: 'FFileHelperModule': undeclared identifier
UATHelper: Packaging (Windows (64-bit)):    /Plugins/FileHelperPlugin/Source/FileHelper/Private/FileHelper.cpp(24): error C2923: 'FStaticallyLinkedModuleRegistrant': 'FFileHelperModule' is not a valid template type argument for parameter 'ModuleClass'
UATHelper: Packaging (Windows (64-bit)):     /Plugins/FileHelperPlugin/Source/FileHelper/Private/FileHelper.cpp(24): error C2514: 'FStaticallyLinkedModuleRegistrant': class template cannot be constructed
UATHelper: Packaging (Windows (64-bit)):     C:\Program Files\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Modules/ModuleManager.h(647): note: see declaration of 'FStaticallyLinkedModuleRegistrant'
UATHelper: Packaging (Windows (64-bit)): Took 11.5877094s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\Locale\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\UBT-DMX_TEST-Win64-Development.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED

**Comment by RLoris** [comment]
Hello, 

Thanks for this information, I will look into this for the next update

4.27 is not yet supported, it will be when 4.27 launched officially and I will update the plugin on the marketplace when the release build is available !

**Comment by zakkar** [comment]
Renaming it as FileHelperLibrary was helpful and works fine
As for the existing class it lives in the following path C:\Program Files\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Misc\FileHelper.h

Good job by the way, it's a helpful tool, still didn't explore most it but it seem to answer my needs, if you need any help also let me know

**Comment by wo2350405615** [comment]
No problem,

**Comment by RLoris** [comment]
@zakkar Hello there, I have updated the plugin on the marketplace for UE4.27 officially, can you confirm that using it does not produce any errors in your project ?

**Comment by RLoris** [comment]
I have tested the plugin myself on 4.27 and not encountered any problem thus I'm closing this issue ! Feel free to reopen it if it does not work for you and I will help you

**Comment by kprimo** [comment]
The same problem was encountered in UE5 Preview2, and the plugin name was changed to FileHelperLibrary to solve it.

**Comment by RLoris** [comment]
Yeah UE5 preview 2 is not supported, when UE5 launches officially the plugin will be recompiled for this version and submitted to the marketplace, that should fix the problem, thanks for the feedback anyway
