### ISSUE TITLE
Unreal Engine 5.5 Support

### ISSUE THREAD

**Issue by doukasd** [RLoris/FileHelperDoc#6]
Hi @RLoris ,

Are you planning to add support for 5.5?

Thank you

**Comment by UnrealMatte** [comment]
+1

**Comment by RLoris** [comment]
Hey there,

Thanks for using my plugins !

All my plugins will be updated to support 5.5. I will need to test and update them during my free time on weekends.

Once the update is submitted and approved by Epic, you will be able to retrieve them directly from fab.

Stay tuned

**Comment by RLoris** [comment]
Hey there,

All my plugins now support unreal engine 5.5 ! They can be retrieved from fab.

Good luck with your projects
